In [39]:
import pandas as pd

In [40]:
try:
    df = pd.read_csv('amazon_product.csv', index_col=0)
except FileNotFoundError:
    raise FileNotFoundError("Path is not valid")

In [41]:
df.head()

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,10,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,8,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,1,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,30,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,2,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN

In [42]:
df.shape

(64, 21)

In [43]:
df.columns

Index(['asin', 'product_title', 'product_price', 'product_original_price',
       'currency', 'product_star_rating', 'product_num_ratings', 'product_url',
       'product_photo', 'product_num_offers', 'product_minimum_offer_price',
       'is_best_seller', 'is_amazon_choice', 'is_prime',
       'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='str')

In [44]:
len(df)

64

In [45]:
df.dtypes

asin                               str
product_title                      str
product_price                      str
product_original_price             str
currency                           str
product_star_rating            float64
product_num_ratings              int64
product_url                        str
product_photo                      str
product_num_offers               int64
product_minimum_offer_price        str
is_best_seller                    bool
is_amazon_choice                  bool
is_prime                          bool
climate_pledge_friendly           bool
sales_volume                       str
delivery                           str
has_variations                    bool
product_availability               str
unit_price                         str
unit_count                     float64
dtype: object

In [46]:
# Keep an untouched copy of the raw data before changing any dtypes
df_raw = df.copy()

In [47]:
price_cols = ['product_price', 'product_original_price', 'product_minimum_offer_price', 'unit_price']
for col in price_cols:
    df[col] = df[col].str.replace('$', '', regex=False).astype(float)


df.dtypes

asin                               str
product_title                      str
product_price                  float64
product_original_price         float64
currency                           str
product_star_rating            float64
product_num_ratings              int64
product_url                        str
product_photo                      str
product_num_offers               int64
product_minimum_offer_price    float64
is_best_seller                    bool
is_amazon_choice                  bool
is_prime                          bool
climate_pledge_friendly           bool
sales_volume                       str
delivery                           str
has_variations                    bool
product_availability               str
unit_price                     float64
unit_count                     float64
dtype: object

In [48]:
df['sales_volume']

0      6K+ bought in past month
1      3K+ bought in past month
2      2K+ bought in past month
3     10K+ bought in past month
4      3K+ bought in past month
                ...
59     50+ bought in past month
60           Print List Price:
61                  Jul 7, 2023
62                 Aug 13, 2024
63    80K+ bought in past month
Name: sales_volume, Length: 64, dtype: str

In [49]:
df2 = pd.read_csv("amazon_product_clean.csv")

In [50]:
df2.dtypes

asin                               str
product_title                      str
product_price                  float64
product_original_price         float64
currency                           str
product_star_rating            float64
product_num_ratings              int64
product_url                        str
product_photo                      str
product_num_offers               int64
product_minimum_offer_price    float64
is_best_seller                    bool
is_amazon_choice                  bool
is_prime                          bool
climate_pledge_friendly           bool
sales_volume                       str
delivery                           str
has_variations                    bool
product_availability               str
unit_price                     float64
unit_count                     float64
dtype: object

In [51]:
df["product_price"]

0      99.99
1     149.74
2      49.88
3     335.00
4     199.99
       ...
59     34.98
60     14.99
61      0.00
62     69.99
63     59.99
Name: product_price, Length: 64, dtype: float64

In [52]:
df["product_price"] <= 50

0     False
1     False
2      True
3     False
4     False
      ...
59     True
60     True
61     True
62    False
63    False
Name: product_price, Length: 64, dtype: bool

In [53]:
df['product_star_rating'].sort_values().head(5)

42    1.8
62    2.6
36    3.2
49    3.2
61    3.5
Name: product_star_rating, dtype: float64

In [54]:
df.sort_values('product_star_rating', ascending=False).head(5)

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
20,B0CRB1VZ46,"Amazon Basics Multipurpose, Comfort Grip, PVD ...",2.39,NaN,USD,4.8,54922,https://www.amazon.com/dp/B0CRB1VZ46,https://m.media-amazon.com/images/I/51XUXWgWF8...,1,...,True,False,True,False,10K+ bought in past month,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,NaN,NaN
19,B0CRDYZVDC,Amazon Basics Heavy Duty Plastic Folders with ...,0.49,NaN,USD,4.8,13638,https://www.amazon.com/dp/B0CRDYZVDC,https://m.media-amazon.com/images/I/61aub4rRv9...,1,...,True,False,True,False,40K+ bought in past month,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,0.25,2.0
37,B0CV4FQPY1,"Bounty Select-A-Size Paper Towels, White, 8 Tr...",22.18,NaN,USD,4.8,36930,https://www.amazon.com/dp/B0CV4FQPY1,https://m.media-amazon.com/images/I/81jYzN4cAd...,1,...,False,False,True,False,60K+ bought in past month,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,2.05,11.0
31,B07RFSSYBH,Atomic Habits: An Easy &amp; Proven Way to Bui...,0.00,18.0,USD,4.8,130395,https://www.amazon.com/dp/B07RFSSYBH,https://m.media-amazon.com/images/I/71F4+7rk2e...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN
17,B0D54JZTHY,Apple AirTag 4 pack,84.99,99.0,USD,4.7,390,https://www.amazon.com/dp/B0D54JZTHY,https://m.media-amazon.com/images/I/61bMNCeAUA...,3,...,False,False,True,False,10K+ bought in past month,"FREE delivery Tue, Aug 6 Or fastest delivery M...",False,NaN,NaN,NaN

In [55]:
df.sort_values('product_num_ratings', ascending=False).head(5)

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
55,B07Y8SJGCV,Disney+,0.0,NaN,USD,4.4,1015448,https://www.amazon.com/dp/B07Y8SJGCV,https://m.media-amazon.com/images/I/719t3jd2Ne...,1,...,False,False,False,False,"Oct 11, 2019",Available instantly on compatible devices,False,NaN,NaN,NaN
56,B005ZXWMUS,Netflix,0.0,NaN,USD,4.6,447888,https://www.amazon.com/dp/B005ZXWMUS,https://m.media-amazon.com/images/I/41Ix1vMUK7...,1,...,False,False,False,False,"Oct 27, 2011",Available instantly on compatible devices,False,NaN,NaN,NaN
23,B08BG9MPT9,Peacock TV,0.0,NaN,USD,4.2,437768,https://www.amazon.com/dp/B08BG9MPT9,https://m.media-amazon.com/images/I/61GbrxjZXH...,1,...,False,False,False,False,"Jun 24, 2021",Available instantly on compatible devices,False,NaN,NaN,NaN
43,B00XZFCVK4,Max,0.0,NaN,USD,4.3,384756,https://www.amazon.com/dp/B00XZFCVK4,https://m.media-amazon.com/images/I/71qqDAb2JG...,1,...,False,False,False,False,"Jul 16, 2015",Available instantly on compatible devices,False,NaN,NaN,NaN
45,B01GGU0XWC,It Ends with Us,0.0,20.24,USD,4.7,333273,https://www.amazon.com/dp/B01GGU0XWC,https://m.media-amazon.com/images/I/815GWEqlkO...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN

In [56]:
df['product_title'][0]

'Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue'

In [57]:
df[df['is_best_seller'] == True]

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
11,B086QB7WZ1,AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless P...,48.75,56.95,USD,4.3,26685,https://www.amazon.com/dp/B086QB7WZ1,https://m.media-amazon.com/images/I/81vjTHTF9W...,4,...,True,False,True,False,5K+ bought in past month,"FREE delivery Wed, Aug 7",False,NaN,NaN,NaN
19,B0CRDYZVDC,Amazon Basics Heavy Duty Plastic Folders with ...,0.49,NaN,USD,4.8,13638,https://www.amazon.com/dp/B0CRDYZVDC,https://m.media-amazon.com/images/I/61aub4rRv9...,1,...,True,False,True,False,40K+ bought in past month,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,0.25,2.0
20,B0CRB1VZ46,"Amazon Basics Multipurpose, Comfort Grip, PVD ...",2.39,NaN,USD,4.8,54922,https://www.amazon.com/dp/B0CRB1VZ46,https://m.media-amazon.com/images/I/51XUXWgWF8...,1,...,True,False,True,False,10K+ bought in past month,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,NaN,NaN
21,1368092209,The Book of Bill (Gravity Falls),18.09,26.99,USD,4.7,180,https://www.amazon.com/dp/1368092209,https://m.media-amazon.com/images/I/81O6JfipQh...,1,...,True,False,True,False,List:,"FREE delivery Wed, Aug 7 on $35 of items shipp...",False,NaN,NaN,NaN
22,1649374186,Onyx Storm (Deluxe Limited Edition) (The Empyr...,19.78,32.99,USD,NaN,0,https://www.amazon.com/dp/1649374186,https://m.media-amazon.com/images/I/9101MLPcFT...,1,...,True,False,False,False,List:,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
24,B0DBD2L1NN,Thanksgiving - UHD/BD Combo + Digital + Steelb...,55.99,NaN,USD,4.0,3075,https://www.amazon.com/dp/B0DBD2L1NN,https://m.media-amazon.com/images/I/81hjnd-mv+...,1,...,True,False,True,False,700+ bought in past month,"FREE delivery Mon, Oct 21 Or fastest delivery ...",False,NaN,NaN,NaN
25,B0CS12LZLS,"NESCAFÉ Gold Espresso Blonde, Instant Coffee, ...",6.68,NaN,USD,4.7,628,https://www.amazon.com/dp/B0CS12LZLS,https://m.media-amazon.com/images/I/71tPLfAAND...,1,...,True,False,True,False,40K+ bought in past month,"FREE delivery Thu, Aug 8 on $35 of items shipp...",False,NaN,1.91,3.0
26,0062300555,Hillbilly Elegy: A Memoir of a Family and Cult...,11.53,18.99,USD,4.4,100331,https://www.amazon.com/dp/0062300555,https://m.media-amazon.com/images/I/81ytGlIkLo...,34,...,True,False,True,False,List:,"FREE delivery Thu, Aug 8 on $35 of items shipp...",False,NaN,NaN,NaN
27,B0DBR4KDRF,FOREVER (Amazon Exclusive Blue Vinyl),36.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0DBR4KDRF,https://m.media-amazon.com/images/I/7175JLEfFw...,1,...,True,False,True,False,NaN,"FREE delivery Tue, Sep 24 Or fastest delivery ...",False,NaN,NaN,NaN
29,B0D5FZGY8W,URO Vaginal Probiotics for Women pH Balance wi...,28.79,31.99,USD,4.5,1142,https://www.amazon.com/dp/B0D5FZGY8W,https://m.media-amazon.com/images/I/61tYAHJi3L...,2,...,True,False,True,False,100K+ bought in past month,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,0.48,60.0
31,B07RFSSYBH,Atomic Habits: An Easy &amp; Proven Way to Bui...,0.00,18.00,USD,4.8,130395,https://www.amazon.com/dp/B07RFSSYBH,https://m.media-amazon.com/images/I/71F4+7rk2e...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN
33,B0C9N2L56X,The Anxious Generation: How the Great Rewiring...,0.00,20.25,USD,4.7,2317,https://www.amazon.com/dp/B0C9N2L56X,https://m.media-amazon.com/images/I/81N4drWaxu...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN
39,052802759X,Rand McNally Large Scale Road Atlas 2025,19.02,29.99,USD,4.7,793,https://www.amazon.com/dp/052802759X,https://m.media-amazon.com/images/I/91CfL2NwfI...,24,...,True,False,True,False,List:,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,NaN,NaN
41,B0D3PBB78P,EA SPORTS College Football 25 - PlayStation 5,67.28,NaN,USD,3.8,96,https://www.amazon.com/dp/B0D3PBB78P,https://m.media-amazon.com/images/I/81aE0GBL2m...,13,...,True,False,True,False,"Jul 19, 2024","FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
45,B01GGU0XWC,It Ends with Us,0.00,20.24,USD,4.7,333273,https://www.amazon.com/dp/B01GGU0XWC,https://m.media-amazon.com/images/I/815GWEqlkO...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN
46,B0DB7CQ965,Star Trek: Prodigy: Season 2 [Blu-Ray],24.49,NaN,USD,NaN,0,https://www.amazon.com/dp/B0DB7CQ965,https://m.media-amazon.com/images/I/81WdJFEK30...,1,...,True,False,True,False,500+ bought in past month,"FREE delivery Mon, Nov 18 on $35 of items ship...",False,NaN,NaN,NaN
47,B0CNG959BT,What Now,11.99,NaN,USD,4.2,51,https://www.amazon.com/dp/B0CNG959BT,https://m.media-amazon.com/images/I/81qIIEWQ+9...,24,...,True,False,True,False,50+ bought in past month,"FREE delivery Tue, Aug 6 on $35 of items shipp...",False,NaN,NaN,NaN
48,B0CPKXGL6Q,All the Colors of the Dark,0.00,22.50,USD,4.6,6346,https://www.amazon.com/dp/B0CPKXGL6Q,https://m.media-amazon.com/images/I/91oSP-pAk1...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN
50,B0CL1YQLB5,The God of the Woods: A Novel,14.99,NaN,USD,4.5,3241,https://www.amazon.com/dp/B0CL1YQLB5,https://m.media-amazon.com/images/I/81WrOo6+IQ...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN
52,B0DB7NV3ZH,Paramount Presents: Ghost [4K UHD + Blu-Ray + ...,39.99,NaN,USD,NaN,0,https://www.amazon.com/dp/B0DB7NV3ZH,https://m.media-amazon.com/images/I/51TcE8-4dU...,1,...,True,False,True,False,900+ bought in past month,"FREE delivery Mon, Oct 28 Or fastest delivery ...",False,NaN,NaN,NaN
57,B0CL72PR7B,A Death in Cornwall: A Novel (Gabriel Allon Bo...,15.99,NaN,USD,4.6,7384,https://www.amazon.com/dp/B0CL72PR7B,https://m.media-amazon.com/images/I/81KoDl1nhV...,1,...,True,False,False,False,Other formats:,Available instantly,False,NaN,NaN,NaN
60,B0CLKQF5HR,Swan Song,14.99,30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,1,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,1,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,1,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN